### ISSUE TITLE
Warning: Native component for "CalendarAndroid" does not exist

### ISSUE THREAD

**Issue by mhinc14** [chymtt/ReactNativeCalendarAndroid#2]
Warning: Native component for "CalendarAndroid" does not exist

I am receiving the above warning, please advise. Thanks

**Comment by chymtt** [comment]
I can't seem to reproduce your warning. Did you follow the exact installation? Can you provide me with your project's gradle files?

**Comment by mhinc14** [comment]
I tried to but it is possible i have made a mistake. I have uploaded both the setting and build gradle files if you would like to have a look :)

[files.zip](https://github.com/chymtt/ReactNativeCalendarAndroid/files/90834/files.zip)

**Comment by mhinc14** [comment]
Closing this issue as it is now working. Unfortunately I do not know why it is working all of a sudden so i can't share a fix. Thank you for your fast response though :)
