### ISSUE TITLE
can i change it style ??? 

### ISSUE THREAD

**Issue by mvpdream** [chymtt/ReactNativeCalendarAndroid#3]
![image](https://cloud.githubusercontent.com/assets/16203724/12413859/bf83cd72-becc-11e5-8a23-128bcb55d498.png)

**Comment by chymtt** [comment]
By style do you mean color? You can use the prop `arrowColor` to change its color. This component currently does not support any other styling though.

**Comment by mvpdream** [comment]
No, I want to change it appearance

**Comment by chymtt** [comment]
Unfortunately, like I've said in my previous comment, the component doesn't support any other kind of styling that arrow yet

**Comment by mvpdream** [comment]
ok
