### ISSUE TITLE
Issue with only seeing red border

### ISSUE THREAD

**Issue by JanMesaric** [chymtt/ReactNativeCalendarAndroid#4]
So I have an exact issue as this guy: http://stackoverflow.com/questions/34897521/react-native-android-calendar-wont-load

I'm using react 0.19.0.

I'm also not sure about where to override the onCreate method. There is in fact a MainActivity.java but there is no onCreate method inside yet. I've just put the whole chunk of code inside for now. 

edit: console throws this:

> W/ReactNativeJS( 3598): Warning: Native component for "Calendar" does not exist

Help would be appreciated,

Sincerely, Jan

**Comment by chymtt** [comment]
This is due to the breaking change that was not mentioned in react-native 0.19.0 release.
@Janckk Please refer to the new README, I've added the section for react-native 0.19.0+
