### ISSUE TITLE
Properties don't seem to be having an effect

### ISSUE THREAD

**Issue by arunabha** [chymtt/ReactNativeCalendarAndroid#5]
It looks like setting properties like selectionColor etc does not take effect. I have the following Calendar component 

```
<Calendar
          width={300}
          topbarVisible={true}
          arrowColor="#dafacd"
          firstDayOfWeek="monday"
          showDate="all"
          currentDate={[ "2016/02/03" ]}
          selectionMode='none'
          selectionColor="#FF0000"
          selectedDates={[ '2016/02/01']} />
```

However as can be seen from the screenshot below, none of those seem to be having an effect (e.g selectionColor is Green instead of FF0000 (red) and the arrowColor is not light green, but black.

Any ideas on how to fix this ?

<img width="668" alt="screen shot 2016-02-13 at 1 46 52 am" src="https://cloud.githubusercontent.com/assets/549722/13027023/dd5622ac-d1f3-11e5-9249-5ce21d40acfd.png">

**Comment by chymtt** [comment]
This is due to the breaking change that was not mentioned in react-native 0.19.0 release
@arunabha Please update and see if the issue has been fixed
